# Generated by Django 3.0.6 on 2020-05-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_ontology_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ontology',
            options={'verbose_name': 'Жоба', 'verbose_name_plural': 'Жобалар'},
        ),
        migrations.AddField(
            model_name='ontology',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Құрылған уақыты'),
        ),
        migrations.AlterField(
            model_name='ontology',
            name='language',
            field=models.CharField(max_length=50, verbose_name='Тілі'),
        ),
        migrations.AlterField(
            model_name='ontology',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Атауы'),
        ),
    ]
